### ISSUE TITLE
请问该框架能否获取请求中的JSON？

### ISSUE THREAD

**Issue by niroshea** [gugemichael/nesty#4]
示例代码中并没有上述问题的功能，在本地实现之后也报错：
java.lang.RuntimeException: Unable to invoke no-args constructor for interface io.netty.handler.codec.http.FullHttpRequest. Register an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:210)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at org.nesty.commons.utils.SerializeUtils.decode(SerializeUtils.java:27)
	at org.nesty.core.server.rest.controller.ControllerMethodDescriptor.parseParam(ControllerMethodDescriptor.java:168)
	at org.nesty.core.server.rest.controller.ControllerMethodDescriptor.resolveParams(ControllerMethodDescriptor.java:156)
	at org.nesty.core.server.rest.controller.ControllerMethodDescriptor.invoke(ControllerMethodDescriptor.java:94)
	at org.nesty.core.server.rest.controller.URLController.call(URLController.java:56)
	at org.nesty.core.server.rest.ExecutorTask.call(ExecutorTask.java:45)
	at org.nesty.core.server.rest.ExecutorTask.call(ExecutorTask.java:21)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

比如如下代码：
public ServiceResponse getProjectById(FullHttpRequest request）｛

ByteBuf jsonBuf = request.content();
        String json = jsonBuf.toString(StandardCharsets.UTF_8);
        System.out.println("JSON :"+json);

｝

**Comment by niroshea** [comment]
OK，我知道如何获取了，@RequestBody String json 。

**Comment by gugemichael** [comment]
@niroshea bingo ~
